### ISSUE TITLE
How to edit to use up to 16 bits ADC resolution ?

### ISSUE THREAD

**Issue by tinamore** [openenergymonitor/EmonLib#15]
Hi.

I want to increase the sensitivity of emon.

I have read in http://www.electricrcaircraftguy.com/2014/05/using-arduino-unos-built-in-16-bit-adc.html#.VXZqDc9sGkp. and i can increment  read resolution 16 bit ADC of arduino to 16 bit ADC read.

Please tell me  where I must edit the in your code to run with 16 BIT ADC emon ?

Thank.

**Comment by officeboy** [comment]
Just set ADC_BITS to whatever your resolution is in emonlib.h.

The code is well documented, you should be able to find what you need.

**Comment by prasadghole** [comment]
Shall we close this issue?
