### ISSUE TITLE
how to calibrate current value?

### ISSUE THREAD

**Issue by bhadanijaydeep** [openenergymonitor/EmonLib#24]
we can't get exact current  value according to original current value......

i used below cod

#include "EmonLib.h"                   
#include <LiquidCrystal.h>
EnergyMonitor emon1;                 
LiquidCrystal lcd(12, 11, 5, 4, 3, 2);
void setup()
{  
  Serial.begin(9600);
    lcd.begin(16, 2);
  lcd.clear();
  emon1.current(0 ,30); 
    lcd.setCursor(0,0);
  lcd.print("Current(A)="); 
}

void loop()
{
  double Irms = emon1.calcIrms(1480);  
 
  Serial.print(Irms*230.0);         
  Serial.print(" ");
  Serial.println(Irms);  
    lcd.setCursor(12,0);
  lcd.print(Irms);       
}

please help me to resolve this problem....

**Comment by glynhudson** [comment]
Please post on our community forums: https://community.openenergymonitor.org/c/getting-started
