### ISSUE TITLE
Library specification (library.properties)

### ISSUE THREAD

**Issue by ricardojlrufino** [openenergymonitor/EmonLib#28]
Please add the library information ( library.properties )
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification

Note: 
I requested the inclusion of this in Arduino  library manager
https://github.com/arduino/Arduino/issues/5399

**Comment by glynhudson** [comment]
We would welcome a pull request for this :-)

I recommend using platfomIO https://platformio.org

**Comment by ricardojlrufino** [comment]
Done.. se PR
