### ISSUE TITLE
Error mesage

### ISSUE THREAD

**Issue by v3nomers** [openenergymonitor/EmonLib#29]
how to solve it

**Comment by v3nomers** [comment]
Arduino: 1.6.8 (Windows 10), Board: "Arduino/Genuino Uno"

C:\Program Files (x86)\Arduino\arduino-builder -dump-prefs -logger=machine -hardware "C:\Program Files (x86)\Arduino\hardware" -hardware "C:\Users\Thomas\AppData\Local\Arduino15\packages" -tools "C:\Program Files (x86)\Arduino\tools-builder" -tools "C:\Program Files (x86)\Arduino\hardware\tools\avr" -tools "C:\Users\Thomas\AppData\Local\Arduino15\packages" -built-in-libraries "C:\Program Files (x86)\Arduino\libraries" -libraries "C:\Users\Thomas\Documents\Arduino\libraries" -fqbn=arduino:avr:uno -ide-version=10608 -build-path "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp" -warnings=none -prefs=build.warn_data_percentage=75 -verbose "C:\Users\Thomas\Documents\Arduino\EmonLib-master\examples\current_only\current_only.ino"
C:\Program Files (x86)\Arduino\arduino-builder -compile -logger=machine -hardware "C:\Program Files (x86)\Arduino\hardware" -hardware "C:\Users\Thomas\AppData\Local\Arduino15\packages" -tools "C:\Program Files (x86)\Arduino\tools-builder" -tools "C:\Program Files (x86)\Arduino\hardware\tools\avr" -tools "C:\Users\Thomas\AppData\Local\Arduino15\packages" -built-in-libraries "C:\Program Files (x86)\Arduino\libraries" -libraries "C:\Users\Thomas\Documents\Arduino\libraries" -fqbn=arduino:avr:uno -ide-version=10608 -build-path "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp" -warnings=none -prefs=build.warn_data_percentage=75 -verbose "C:\Users\Thomas\Documents\Arduino\EmonLib-master\examples\current_only\current_only.ino"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10608 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Users\Thomas\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.6.11\cores\arduino" "-IC:\Users\Thomas\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.6.11\variants\standard" "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\sketch\current_only.ino.cpp" -o "nul"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10608 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Users\Thomas\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.6.11\cores\arduino" "-IC:\Users\Thomas\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.6.11\variants\standard" "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\sketch\current_only.ino.cpp" -o "nul"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10608 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Users\Thomas\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.6.11\cores\arduino" "-IC:\Users\Thomas\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.6.11\variants\standard" "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\sketch\current_only.ino.cpp" -o "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\preproc\ctags_target_for_gcc_minus_e.cpp"
"C:\Program Files (x86)\Arduino\tools-builder\ctags\5.8-arduino10/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\preproc\ctags_target_for_gcc_minus_e.cpp"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10608 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Users\Thomas\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.6.11\cores\arduino" "-IC:\Users\Thomas\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.6.11\variants\standard" "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\sketch\current_only.ino.cpp" -o "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\sketch\current_only.ino.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-gcc" -c -g -x assembler-with-cpp -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10608 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Users\Thomas\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.6.11\cores\arduino" "-IC:\Users\Thomas\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.6.11\variants\standard" "C:\Users\Thomas\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.6.11\cores\arduino\wiring_pulse.S" -o "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\wiring_pulse.S.o"
Using previously compiled file: C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\WInterrupts.c.o
Using previously compiled file: C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\hooks.c.o
Using previously compiled file: C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\wiring.c.o
Using previously compiled file: C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\wiring_analog.c.o
Using previously compiled file: C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\wiring_digital.c.o
Using previously compiled file: C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\wiring_pulse.c.o
Using previously compiled file: C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\wiring_shift.c.o
Using previously compiled file: C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\CDC.cpp.o
Using previously compiled file: C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\HardwareSerial.cpp.o
Using previously compiled file: C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\HardwareSerial0.cpp.o
Using previously compiled file: C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\HardwareSerial1.cpp.o
Using previously compiled file: C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\HardwareSerial2.cpp.o
Using previously compiled file: C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\HardwareSerial3.cpp.o
Using previously compiled file: C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\IPAddress.cpp.o
Using previously compiled file: C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\PluggableUSB.cpp.o
Using previously compiled file: C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\Print.cpp.o
Using previously compiled file: C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\Stream.cpp.o
Using previously compiled file: C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\Tone.cpp.o
Using previously compiled file: C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\USBCore.cpp.o
Using previously compiled file: C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\WMath.cpp.o
Using previously compiled file: C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\WString.cpp.o
Using previously compiled file: C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\abi.cpp.o
Using previously compiled file: C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\main.cpp.o
Using previously compiled file: C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\new.cpp.o
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\core.a" "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\wiring_pulse.S.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\core.a" "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\WInterrupts.c.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\core.a" "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\hooks.c.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\core.a" "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\wiring.c.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\core.a" "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\wiring_analog.c.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\core.a" "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\wiring_digital.c.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\core.a" "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\wiring_pulse.c.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\core.a" "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\wiring_shift.c.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\core.a" "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\CDC.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\core.a" "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\HardwareSerial.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\core.a" "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\HardwareSerial0.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\core.a" "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\HardwareSerial1.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\core.a" "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\HardwareSerial2.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\core.a" "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\HardwareSerial3.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\core.a" "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\IPAddress.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\core.a" "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\PluggableUSB.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\core.a" "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\Print.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\core.a" "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\Stream.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\core.a" "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\Tone.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\core.a" "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\USBCore.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\core.a" "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\WMath.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\core.a" "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\WString.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\core.a" "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\abi.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\core.a" "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\main.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-ar" rcs  "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\core.a" "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\core\new.cpp.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-gcc" -w -Os -Wl,--gc-sections -mmcu=atmega328p  -o "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp/current_only.ino.elf" "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\sketch\current_only.ino.cpp.o" "C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp/core\core.a" "-LC:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp" -lm
C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\sketch\current_only.ino.cpp.o: In function `setup':

C:\Users\Thomas\Documents\Arduino\EmonLib-master\examples\current_only/current_only.ino:9: undefined reference to `EnergyMonitor::current(unsigned int, double)'

C:\Users\Thomas\AppData\Local\Temp\build03daa4c523108ec5d5526b9f8bce401d.tmp\sketch\current_only.ino.cpp.o: In function `loop':

C:\Users\Thomas\Documents\Arduino\EmonLib-master\examples\current_only/current_only.ino:14: undefined reference to `EnergyMonitor::calcIrms(unsigned int)'

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino/Genuino Uno.

**Comment by glynhudson** [comment]
Please post on our community forum. This is not an issue with emonlib

https://community.openenergymonitor.org

- sent from my mobile device
