### ISSUE TITLE
total power real power consumption 

### ISSUE THREAD

**Issue by ahmedtayeh** [openenergymonitor/EmonLib#32]
I am wondering how can i calculate the total real power consumption lets say for one whole month? any suggestion for the modification i need to do. thanks

**Comment by glynhudson** [comment]
This can be done in emoncms input processing.

- sent from my mobile device

**Comment by ahmedtayeh** [comment]
great but if i had an internet disconnection, i will lose the data in this case right ?

**Comment by glynhudson** [comment]
Correct, you should use a wh accumulator sketch to keep a record of wh
elapsed on online  device:

https://github.com/openenergymonitor/emonTxFirmware/tree/master/emonTxV2/emonTx_continuous_watthours

- sent from my mobile device
