### ISSUE TITLE
How to monitor real power,reactive power,apparent power,Powerfactor,cost of power consumed

### ISSUE THREAD

**Issue by jamipraveeen** [openenergymonitor/EmonLib#36]
In the following example folder I can find only two ino files (current only and voltage and current only).But, I want to monitor real power,reactive power,apparent power,powerfactor,cost of power consumed.what are the lines of code I must add in the sketch to get the data of parameters

**Comment by glynhudson** [comment]
See L19 - L23, of the voltage sketch:  

https://github.com/openenergymonitor/EmonLib/blob/master/examples/voltage_and_current/voltage_and_current.ino#L19
