### ISSUE TITLE
Not a issue but a question

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [openenergymonitor/EmonLib#52]
Hello I'm a little lost. on coding. I'm not a coder at all much. I really need help. I don't have a 33 ohms resistor for the Burden resistor i do how ever have a 30 ohms resistor. Can someone please help me to calculate it into the Current only example?

Joseph

**Comment by glynhudson** [comment]
Please post on our community forum, will do our best to help https://community.openenergymonitor.org

Have you seen this documentation for calculating burden resistor: https://learn.openenergymonitor.org/electricity-monitoring/ct-sensors/interface-with-arduino
